# 🚀 SABER ENTERPRISES - UNIVERSAL PROJECT GIT SETUP
# Auto-initialize Git for any new project in VS Code

param(
    [Parameter(Mandatory=$false)]
    [string]$ProjectName = (Split-Path -Leaf (Get-Location)),
    
    [Parameter(Mandatory=$false)]
    [string]$ProjectDescription = "New project by Saber Enterprises"
)

Write-Host "================================================" -ForegroundColor Cyan
Write-Host "🚀 SABER ENTERPRISES - GIT AUTO-SETUP" -ForegroundColor Green
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

$currentDir = Get-Location
Write-Host "📁 Project Directory: $currentDir" -ForegroundColor Yellow
Write-Host "🏷️  Project Name: $ProjectName" -ForegroundColor Yellow
Write-Host "📝 Description: $ProjectDescription" -ForegroundColor Yellow
Write-Host ""

# Check if Git is available
try {
    $gitVersion = git --version 2>$null
    Write-Host "✅ Git Available: $gitVersion" -ForegroundColor Green
} catch {
    Write-Host "❌ ERROR: Git not found! Please install Git first." -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

# Check if already a Git repository
if (Test-Path ".git") {
    Write-Host "⚠️  This directory is already a Git repository!" -ForegroundColor Yellow
    $continue = Read-Host "Continue anyway? (y/N)"
    if ($continue -ne "y" -and $continue -ne "Y") {
        Write-Host "Cancelled." -ForegroundColor Yellow
        exit 0
    }
}

Write-Host "🔧 Initializing Git repository..." -ForegroundColor Yellow

# Initialize Git repository
git init

# Set up Git configuration (already global, but confirm)
Write-Host "⚙️  Configuring Git settings..." -ForegroundColor Yellow
git config user.name "Saber Enterprises"
git config user.email "saber.enterprises.dev@gmail.com"
git config init.defaultBranch main

# Create comprehensive .gitignore
Write-Host "🚫 Creating .gitignore file..." -ForegroundColor Yellow
$gitignoreContent = @"
# $ProjectName - Git Ignore File
# Generated by Saber Enterprises Universal Git Setup

# Operating System Files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
desktop.ini

# IDE/Editor Files
.idea/
*.swp
*.swo
*~

# Temporary Files
*.tmp
*.temp
temp_*
*.log

# Browser Cache & Storage
*.cache
*.storage

# Backup Files
*.bak
*.backup

# Node.js (if applicable)
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
package-lock.json.bak

# Build/Dist Folders
dist/
build/
out/

# Environment Files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Archives
*.zip
*.tar.gz
*.rar

# Large Media Files
*.mp4
*.avi
*.mov
*.mkv

# Installer Files
*.exe
*.msi
*.dmg
*.pkg

# Project-specific ignores (add below)
"@

$gitignoreContent | Out-File -FilePath ".gitignore" -Encoding UTF8

# Create README.md
Write-Host "📄 Creating README.md..." -ForegroundColor Yellow
$readmeContent = @"
# $ProjectName

$ProjectDescription

## 🚀 Features

- Add your project features here
- Built with professional development practices
- Version controlled with Git
- VS Code optimized

## 🛠 Setup

1. Clone or download this repository
2. Open in VS Code
3. Start developing!

## 📁 Project Structure

```
$ProjectName/
├── README.md           # This file
├── .gitignore         # Git ignore rules
└── (your project files)
```

## 🎯 Development

This project is set up with:
- ✅ Git version control
- ✅ VS Code integration
- ✅ Professional workflow
- ✅ Comprehensive documentation

## 📝 License

© $(Get-Date -Format 'yyyy') Saber Enterprises. All rights reserved.

---

*Built with ❤️ by Saber Enterprises*
"@

$readmeContent | Out-File -FilePath "README.md" -Encoding UTF8

# Create VS Code settings
Write-Host "⚙️  Setting up VS Code configuration..." -ForegroundColor Yellow
if (-not (Test-Path ".vscode")) {
    New-Item -ItemType Directory -Path ".vscode" | Out-Null
}

$vscodeSettings = @"
{
  "git.enabled": true,
  "git.autofetch": true,
  "git.confirmSync": false,
  "git.enableSmartCommit": true,
  "git.suggestSmartCommit": true,
  "git.autoStash": true,
  "git.showPushSuccessNotification": true,
  "git.timeline.enabled": true,
  "git.openRepositoryInParentFolders": "always",
  "scm.defaultViewMode": "tree",
  "scm.alwaysShowRepositories": true,
  "scm.autoReveal": true,
  "editor.rulers": [80, 120],
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true
  },
  "search.exclude": {
    "**/.git": true,
    "**/node_modules": true
  }
}
"@

$vscodeSettings | Out-File -FilePath ".vscode/settings.json" -Encoding UTF8

# Add all files and create initial commit
Write-Host "📦 Adding files to Git..." -ForegroundColor Yellow
git add .

Write-Host "💾 Creating initial commit..." -ForegroundColor Yellow
$commitMessage = @"
Initial commit: $ProjectName

🎯 Project: $ProjectDescription
✅ Git repository initialized
✅ VS Code integration configured
✅ Professional development setup
✅ Documentation created

Generated by Saber Enterprises Universal Git Setup 🚀
"@

git commit -m $commitMessage

Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "🎉 GIT SETUP COMPLETE!" -ForegroundColor Green
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "📊 Repository Status:" -ForegroundColor Yellow
git status --short
git log --oneline -1

Write-Host ""
Write-Host "🔗 Next Steps:" -ForegroundColor Yellow
Write-Host "1. 🌐 Create GitHub repository: https://github.com/new" -ForegroundColor Cyan
Write-Host "2. 🔗 Connect remote: git remote add origin <repo-url>" -ForegroundColor Cyan
Write-Host "3. 📤 Push: git push -u origin main" -ForegroundColor Cyan
Write-Host ""

Write-Host "⚡ Quick Commands:" -ForegroundColor Yellow
Write-Host "• git st      # Status" -ForegroundColor Cyan
Write-Host "• git add .   # Stage all" -ForegroundColor Cyan
Write-Host "• git cm -m 'message'  # Commit" -ForegroundColor Cyan
Write-Host "• git push    # Push to remote" -ForegroundColor Cyan
Write-Host ""

Write-Host "✅ Your project is ready for professional development!" -ForegroundColor Green
Write-Host "🎵 Happy coding! - Saber Enterprises" -ForegroundColor Magenta

Read-Host "Press Enter to continue"
